name: Check Markdown links

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "0 0 * * 0"

jobs:
  build:
    name: Check links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run check links script
      run: |
        ls -a
